version: '3'
services:
  web:
    #image: php:7.3-apache
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: injectme-webserver
    volumes:
      - ./:/var/www/html/
    ports:
      - 8008:80

  db:
    container_name: injectme-sqlserver
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loginTest
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - 6033:3306